# Generated by Django 4.2 on 2024-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/fallback.png', upload_to='profile_pictures/'),
        ),
    ]
