# Generated by Django 5.0.6 on 2024-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_2fa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='sms_2fa_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
