# Generated by Django 5.0.6 on 2024-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_qr_2fa_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='qr_2fa_active',
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
    ]
