# Generated by Django 5.0.6 on 2024-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_qr_2fa_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
