# Generated by Django 5.0.6 on 2024-09-06 07:42

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=player.models.upload_to_profile_pictures),
        ),
    ]
