# Generated by Django 5.0.6 on 2024-09-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_player_is_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_profile_picture',
        ),
        migrations.AddField(
            model_name='player',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
