# Generated by Django 5.0.6 on 2024-09-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_player_connected_alter_player_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='connected',
            new_name='layout_exception',
        ),
    ]
