# Generated by Django 5.0.6 on 2024-09-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_rename_connected_player_layout_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='layout_exception',
        ),
    ]
