# Generated by Django 5.0.7 on 2024-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_remove_player_layout_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/fallback.png', null=True, upload_to='profile_pictures'),
        ),
    ]
