services:
    redis:
      container_name: redis
      image: "redis:7"
      restart: always
      ports:
        - "8379:6379"
      networks:
        - ft_transcendence
    postgresql:
      container_name: postgresql
      image: postgres:16.1
      restart: always
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data 
      networks:
        - ft_transcendence
    django:
        build:
            context: django
        container_name: django_app
        expose:
            - "8000:8000"
        restart: on-failure
        networks: 
          - ft_transcendence
        depends_on:
          - postgresql
        env_file:
          .env
    nginx:
        image: nginx
        container_name: nginx_server
        ports:
          - "8080:8080"
          - "8443:8443"       
        networks:
          - ft_transcendence
        build:
          context: ./
          dockerfile: ./nginx/Dockerfile
        restart: on-failure
        depends_on:
          - django

volumes:
    static_volume:
    media_volume:
    postgres_data:
      driver: local
    protonmail_config:

networks:
    ft_transcendence:
      driver: bridge
